# The docker-compose.yml file describes the services that make your app. 
# In this example those services are a web server and database. The compose file also describes which Docker images these services use, 
# how they link together, any volumes they might need to be mounted inside the containers.
#  Finally, the docker-compose.yml file describes which ports these services expose. 

version: "3"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db