# Compose template version 3.9
version: "3"
services:
  # The web service uses an image that’s built from the Dockerfile in the current directory
  web:
    build: .
    ports:
      - "5000:5000"
      #The new volumes key mounts the project directory (current directory) on the host to /code inside the container, 
      # allowing you to modify the code on the fly, without having to rebuild the image. The environment key sets the FLASK_ENV environment 
      # variable, which tells flask run to run in development mode and reload the code on change. This mode should only be used in development.
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
    stdin_open: true # docker run -i
    tty: true        # docker run -t
  redis:
    image: "redis:alpine"